
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
      - ./database:/app/database
    environment:
      - NODE_ENV=development
    restart: unless-stopped

volumes:
  sqlite_data:
