
version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./database:/app/database
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  db:
    image: alpine:latest
    volumes:
      - sqlite_data:/data
      - ./database:/app/database
    command: tail -f /dev/null

volumes:
  sqlite_data:
